spring.application.name=studyhub
spring.datasource.url = postgresql://dpg-d8g7d1urnols73dadv8g-a/${DB_NAME}
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driverClassName = org.postgresql.Drive